# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#

workflows:
    version: 2
    workflow:
        jobs:
            - build
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk-node-browsers

    working_directory: ~/repo

    environment:
      CASSANDRA_VERSION: 3.11.2

    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: |
              sudo apt-get update -qq
              sudo apt-get install -y libjna-java python-dev python-pip libyaml-dev nodejs
              sudo pip install pyYaml ccm
              sudo npm install -g bower > /dev/null

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
            - ~/.ccm/repository
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Test non-incremental in-memory Reaper
          command: |
              bash .circleci/setup-ccm.sh
              MAVEN_OPTS="-Xmx1g" mvn clean install
              mvn surefire:test -Dtest=ReaperNoIncrementalIT
              mvn surefire:test -Dtest=ReaperH2NoIncrementalIT

      - run:
          name: Test non-incremental single Reaper on Cassandra
          command: |
              bash .circleci/setup-ccm.sh
              MAVEN_OPTS="-Xmx1g" mvn clean install -DskipTests
              #mvn surefire:test -Dtest=ReaperPostgresIT # TODO set up postgres
              mvn surefire:test -DsurefireArgLine="-Xmx1g" -Dtest=ReaperCassandraNoIncrementalIT

      - run:
          name: Test non-incremental stable Reapers on Cassandra
          command: |
              bash .circleci/setup-ccm.sh
              MAVEN_OPTS="-Xmx1g" mvn clean install -DskipTests
              mvn surefire:test -DsurefireArgLine="-Xmx1g" -Dtest=ReaperCassandraNoIncrementalIT -Dgrim.reaper.min=2 -Dgrim.reaper.max=2

      - run:
          name: Test non-incremental unstable Reapers on Cassandra
          command: |
              bash .circleci/setup-ccm.sh
              MAVEN_OPTS="-Xmx1g" mvn clean install -DskipTests
              mvn surefire:test -DsurefireArgLine="-Xmx1g" -Dtest=ReaperCassandraNoIncrementalIT -Dgrim.reaper.min=2 -Dgrim.reaper.max=4

      - run:
          name: Test multi-DC Cassandra
          command: |
              bash .circleci/setup-ccm.sh
              MAVEN_OPTS="-Xmx1g" mvn clean install -DskipTests
              sed -i 's/etc\/cassandra\/jmxremote.password/home\/circleci\/.local\/jmxremote.password/' /home/circleci/.ccm/test/node3/conf/cassandra-env.sh
              sed -i 's/etc\/cassandra\/jmxremote.password/home\/circleci\/.local\/jmxremote.password/' /home/circleci/.ccm/test/node4/conf/cassandra-env.sh
              ccm node3 stop
              ccm node3 start
              ccm node4 stop
              ccm node4 start
              mvn surefire:test -DsurefireArgLine="-Xmx1g" -Dtest=ReaperCassandraIncrementalIT -Dgrim.reaper.min=2 -Dgrim.reaper.max=4

      - store_test_results:
          path: src/server/target/surefire-reports


notify:
  webhooks:
    # A list of hook hashes, containing the url field
    # gitter hook
    - url: https://webhooks.gitter.im/e/5ef39c9d96700ef6954d

